let form: any = document.getElementById("form");
let username: any = document.getElementById("name");
let profession: any = document.getElementById("Profession");
let email: any = document.getElementById("email");
let address: any = document.getElementById("add");
let usercontact: any = document.getElementById("contact");
let aboutme: any = document.getElementById("aboutme");
let Pic: any = document.getElementById("pic");
let degree1: any = document.getElementById("deg1");
let institue1: any = document.getElementById("inst1");
let start_year1: any = document.getElementById("start");
let deg_info1: any = document.getElementById("deginfo1");
let degree2: any = document.getElementById("deg2");
let institue2: any = document.getElementById("inst2");
let start_year2: any = document.getElementById("start-year");
let deg_info2: any = document.getElementById("deginfo2");
let job_name1: any = document.getElementById("job-name1");
let company1: any = document.getElementById("company1");
let job_start_year1: any = document.getElementById("job-s-y1");
let job_info1: any = document.getElementById("jobinfo1");
let job_name2: any = document.getElementById("job-name2");
let company2: any = document.getElementById("company2");
let job_start_year2: any = document.getElementById("job-s-y2");
let job_info2: any = document.getElementById("jobinfo2");
let skill1: any = document.getElementById("skill1");
let skill2: any = document.getElementById("skill2");
let skill3: any = document.getElementById("skill3");
let skill4: any = document.getElementById("skill4");
let skill5: any = document.getElementById("skill5");
let skill6: any = document.getElementById("skill6");
let skill7: any = document.getElementById("skill7");
let lang1: any = document.getElementById("lang1");
let lang2: any = document.getElementById("lang2");
let lang3: any = document.getElementById("lang3");
let lang4: any = document.getElementById("lang4");
let awa_year1: any = document.getElementById("awa-year1");
let comp_name1: any = document.getElementById("comp-name1");
let title1: any = document.getElementById("title1");
let awa_year2: any = document.getElementById("awa-year2");
let comp_name2: any = document.getElementById("comp-name2");
let title2: any = document.getElementById("title2");

form?.addEventListener("submit", (e: Event) => {
  e.preventDefault();

  localStorage.setItem("name", username.value);
  localStorage.setItem("profession", profession.value);
  localStorage.setItem("email", email.value);
  localStorage.setItem("address", address.value);
  localStorage.setItem("contact", usercontact.value);
  localStorage.setItem("aboutme", aboutme.value);
  localStorage.setItem("degree1", degree1.value);
  localStorage.setItem("institue1", institue1.value);
  localStorage.setItem("start_year1", start_year1.value);
  localStorage.setItem("deginfo1", deg_info1.value);
  localStorage.setItem("degree2", degree2.value);
  localStorage.setItem("institue2", institue2.value);
  localStorage.setItem("start_year2", start_year2.value);
  localStorage.setItem("deginfo2", deg_info2.value);
  localStorage.setItem("job_name1", job_name1.value);
  localStorage.setItem("company1", company1.value);
  localStorage.setItem("job_start_year1", job_start_year1.value);
  localStorage.setItem("job_info1", job_info1.value);
  localStorage.setItem("job_name2", job_name2.value);
  localStorage.setItem("company2", company2.value);
  localStorage.setItem("job_start_year2", job_start_year2.value);
  localStorage.setItem("job_info2", job_info2.value);
  localStorage.setItem("skill1", skill1.value);
  localStorage.setItem("skill2", skill2.value);
  localStorage.setItem("skill3", skill3.value);
  localStorage.setItem("skill4", skill4.value);
  localStorage.setItem("skill5", skill5.value);
  localStorage.setItem("skill6", skill6.value);
  localStorage.setItem("skill7", skill7.value);
  localStorage.setItem("lang1", lang1.value);
  localStorage.setItem("lang2", lang2.value);
  localStorage.setItem("lang3", lang3.value);
  localStorage.setItem("lang4", lang4.value);
  localStorage.setItem("awa_year1", awa_year1.value);
  localStorage.setItem("comp_name1", comp_name1.value);
  localStorage.setItem("title1", title1.value);
  localStorage.setItem("awa_year2", awa_year2.value);
  localStorage.setItem("comp_name2", comp_name2.value);
  localStorage.setItem("title2", title2.value);

  if (Pic.files && Pic.files[0]) {
    let reader = new FileReader();
    reader.addEventListener("load", () => {
      let textimg: any = reader.result;
      localStorage.setItem("profile", textimg);
    });
    reader.readAsDataURL(Pic.files[0]);
  }
  window.location.href="/Resume/resume.html"
});
